### ISSUE TITLE
Are array filters supported?

### ISSUE THREAD

**Issue by igregson** [rasteiner/k3-pagesdisplay-section#14]
Greetings,

First off, thank you for this! I was surprised to learn that Kirby doesn't allow for filtering pages in page section out-of-the-box.

I've run into an issue trying to use an array filter. 

I've outlined my question here: https://forum.getkirby.com/t/query-to-filter-page-by-current-pages-path-in-page-fields-array/25312/1

Not sure if the issue could be on the plugin end or not but wanted to check. If not, feel free to simply close this!

**Comment by rasteiner** [comment]
The plugin doesn't really add anything to the Kirby's query syntax, and that one just calls the PHP api. So if the filter isn't working as expected, it's most probably due to the filter, and not to the query. 

As a test you can try running the same filter in your template, just using the PHP api, and see if it works there. 
So I'm gonna close this, I've answered you on the forum :)

cheers
